/**
 * The complete 6502 (NES CPU) Opcode table.
 * Keyed by the 8-bit hexadecimal opcode value.
 *
 * flags_mod Key:
 * - '*': Affected (Set or cleared based on result)
 * - '-': Unaffected
 * - '0': Always Cleared
 * - '1': Always Set
 * - 'x': Special State (Value restored from stack for PLP/RTI)
 */
export const NESOPC = {
  "00": {"mnemonic": "BRK", "mode": "IMP", "bytes": 1, "cycles": 7, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "1", "D": "-"}},
  "01": {"mnemonic": "ORA", "mode": "IND_X", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "02": {"mnemonic": "JAM", "mode": "IMP", "bytes": 1, "cycles": 0, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "03": {"mnemonic": "SLO", "mode": "IND_X", "bytes": 2, "cycles": 8, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "04": {"mnemonic": "NOP", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "05": {"mnemonic": "ORA", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "06": {"mnemonic": "ASL", "mode": "ZP", "bytes": 2, "cycles": 5, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "07": {"mnemonic": "SLO", "mode": "ZP", "bytes": 2, "cycles": 5, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "08": {"mnemonic": "PHP", "mode": "IMP", "bytes": 1, "cycles": 3, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "09": {"mnemonic": "ORA", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "0A": {"mnemonic": "ASL", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "0B": {"mnemonic": "ANC", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "0C": {"mnemonic": "NOP", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "0D": {"mnemonic": "ORA", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "0E": {"mnemonic": "ASL", "mode": "ABS", "bytes": 3, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "0F": {"mnemonic": "SLO", "mode": "ABS", "bytes": 3, "cycles": 6, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "10": {"mnemonic": "BPL", "mode": "REL", "bytes": 2, "cycles": 2, "unofficial": false, "branch_cycles": 2, "page_cycles": 1, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "11": {"mnemonic": "ORA", "mode": "IND_Y", "bytes": 2, "cycles": 5, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "12": {"mnemonic": "JAM", "mode": "IMP", "bytes": 1, "cycles": 0, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "13": {"mnemonic": "SLO", "mode": "IND_Y", "bytes": 2, "cycles": 8, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "14": {"mnemonic": "NOP", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "15": {"mnemonic": "ORA", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "16": {"mnemonic": "ASL", "mode": "ZP_X", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "17": {"mnemonic": "SLO", "mode": "ZP_X", "bytes": 2, "cycles": 6, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "18": {"mnemonic": "CLC", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "0", "V": "-", "I": "-", "D": "-"}},
  "19": {"mnemonic": "ORA", "mode": "ABS_Y", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "1A": {"mnemonic": "NOP", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "1B": {"mnemonic": "SLO", "mode": "ABS_Y", "bytes": 3, "cycles": 7, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "1C": {"mnemonic": "NOP", "mode": "ABS_X", "bytes": 3, "cycles": 4, "unofficial": true, "page_cycles": 1, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "1D": {"mnemonic": "ORA", "mode": "ABS_X", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "1E": {"mnemonic": "ASL", "mode": "ABS_X", "bytes": 3, "cycles": 7, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "1F": {"mnemonic": "SLO", "mode": "ABS_X", "bytes": 3, "cycles": 7, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "20": {"mnemonic": "JSR", "mode": "ABS", "bytes": 3, "cycles": 6, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "21": {"mnemonic": "AND", "mode": "IND_X", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "22": {"mnemonic": "JAM", "mode": "IMP", "bytes": 1, "cycles": 0, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "23": {"mnemonic": "RLA", "mode": "IND_X", "bytes": 2, "cycles": 8, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "24": {"mnemonic": "BIT", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "*", "I": "-", "D": "-"}},
  "25": {"mnemonic": "AND", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "26": {"mnemonic": "ROL", "mode": "ZP", "bytes": 2, "cycles": 5, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "27": {"mnemonic": "RLA", "mode": "ZP", "bytes": 2, "cycles": 5, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "28": {"mnemonic": "PLP", "mode": "IMP", "bytes": 1, "cycles": 4, "unofficial": false, "flags_mod": {"N": "x", "Z": "x", "C": "x", "V": "x", "I": "x", "D": "x"}},
  "29": {"mnemonic": "AND", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "2A": {"mnemonic": "ROL", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "2B": {"mnemonic": "ANC", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "2C": {"mnemonic": "BIT", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "*", "I": "-", "D": "-"}},
  "2D": {"mnemonic": "AND", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "2E": {"mnemonic": "ROL", "mode": "ABS", "bytes": 3, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "2F": {"mnemonic": "RLA", "mode": "ABS", "bytes": 3, "cycles": 6, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "30": {"mnemonic": "BMI", "mode": "REL", "bytes": 2, "cycles": 2, "unofficial": false, "branch_cycles": 2, "page_cycles": 1, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "31": {"mnemonic": "AND", "mode": "IND_Y", "bytes": 2, "cycles": 5, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "32": {"mnemonic": "JAM", "mode": "IMP", "bytes": 1, "cycles": 0, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "33": {"mnemonic": "RLA", "mode": "IND_Y", "bytes": 2, "cycles": 8, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "34": {"mnemonic": "NOP", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "35": {"mnemonic": "AND", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "36": {"mnemonic": "ROL", "mode": "ZP_X", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "37": {"mnemonic": "RLA", "mode": "ZP_X", "bytes": 2, "cycles": 6, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "38": {"mnemonic": "SEC", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "1", "V": "-", "I": "-", "D": "-"}},
  "39": {"mnemonic": "AND", "mode": "ABS_Y", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "3A": {"mnemonic": "NOP", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "3B": {"mnemonic": "RLA", "mode": "ABS_Y", "bytes": 3, "cycles": 7, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "3C": {"mnemonic": "NOP", "mode": "ABS_X", "bytes": 3, "cycles": 4, "unofficial": true, "page_cycles": 1, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "3D": {"mnemonic": "AND", "mode": "ABS_X", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "3E": {"mnemonic": "ROL", "mode": "ABS_X", "bytes": 3, "cycles": 7, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "3F": {"mnemonic": "RLA", "mode": "ABS_X", "bytes": 3, "cycles": 7, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "40": {"mnemonic": "RTI", "mode": "IMP", "bytes": 1, "cycles": 6, "unofficial": false, "flags_mod": {"N": "x", "Z": "x", "C": "x", "V": "x", "I": "x", "D": "x"}},
  "41": {"mnemonic": "EOR", "mode": "IND_X", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "42": {"mnemonic": "JAM", "mode": "IMP", "bytes": 1, "cycles": 0, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "43": {"mnemonic": "SRE", "mode": "IND_X", "bytes": 2, "cycles": 8, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "44": {"mnemonic": "NOP", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "45": {"mnemonic": "EOR", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "46": {"mnemonic": "LSR", "mode": "ZP", "bytes": 2, "cycles": 5, "unofficial": false, "flags_mod": {"N": "0", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "47": {"mnemonic": "SRE", "mode": "ZP", "bytes": 2, "cycles": 5, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "48": {"mnemonic": "PHA", "mode": "IMP", "bytes": 1, "cycles": 3, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "49": {"mnemonic": "EOR", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "4A": {"mnemonic": "LSR", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "0", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "4B": {"mnemonic": "ALR", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "4C": {"mnemonic": "JMP", "mode": "ABS", "bytes": 3, "cycles": 3, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "4D": {"mnemonic": "EOR", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "4E": {"mnemonic": "LSR", "mode": "ABS", "bytes": 3, "cycles": 6, "unofficial": false, "flags_mod": {"N": "0", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "4F": {"mnemonic": "SRE", "mode": "ABS", "bytes": 3, "cycles": 6, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "50": {"mnemonic": "BVC", "mode": "REL", "bytes": 2, "cycles": 2, "unofficial": false, "branch_cycles": 2, "page_cycles": 1, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "51": {"mnemonic": "EOR", "mode": "IND_Y", "bytes": 2, "cycles": 5, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "52": {"mnemonic": "JAM", "mode": "IMP", "bytes": 1, "cycles": 0, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "53": {"mnemonic": "SRE", "mode": "IND_Y", "bytes": 2, "cycles": 8, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "54": {"mnemonic": "NOP", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "55": {"mnemonic": "EOR", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "56": {"mnemonic": "LSR", "mode": "ZP_X", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "0", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "57": {"mnemonic": "SRE", "mode": "ZP_X", "bytes": 2, "cycles": 6, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "58": {"mnemonic": "CLI", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "0", "D": "-"}},
  "59": {"mnemonic": "EOR", "mode": "ABS_Y", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "5A": {"mnemonic": "NOP", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "5B": {"mnemonic": "SRE", "mode": "ABS_Y", "bytes": 3, "cycles": 7, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "5C": {"mnemonic": "NOP", "mode": "ABS_X", "bytes": 3, "cycles": 4, "unofficial": true, "page_cycles": 1, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "5D": {"mnemonic": "EOR", "mode": "ABS_X", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "5E": {"mnemonic": "LSR", "mode": "ABS_X", "bytes": 3, "cycles": 7, "unofficial": false, "flags_mod": {"N": "0", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "5F": {"mnemonic": "SRE", "mode": "ABS_X", "bytes": 3, "cycles": 7, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "60": {"mnemonic": "RTS", "mode": "IMP", "bytes": 1, "cycles": 6, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "61": {"mnemonic": "ADC", "mode": "IND_X", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "62": {"mnemonic": "JAM", "mode": "IMP", "bytes": 1, "cycles": 0, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "63": {"mnemonic": "RRA", "mode": "IND_X", "bytes": 2, "cycles": 8, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "64": {"mnemonic": "NOP", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "65": {"mnemonic": "ADC", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "66": {"mnemonic": "ROR", "mode": "ZP", "bytes": 2, "cycles": 5, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "67": {"mnemonic": "RRA", "mode": "ZP", "bytes": 2, "cycles": 5, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "68": {"mnemonic": "PLA", "mode": "IMP", "bytes": 1, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "69": {"mnemonic": "ADC", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "6A": {"mnemonic": "ROR", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "6B": {"mnemonic": "ARR", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "6C": {"mnemonic": "JMP", "mode": "IND", "bytes": 3, "cycles": 5, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "6D": {"mnemonic": "ADC", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "6E": {"mnemonic": "ROR", "mode": "ABS", "bytes": 3, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "6F": {"mnemonic": "RRA", "mode": "ABS", "bytes": 3, "cycles": 6, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "70": {"mnemonic": "BVS", "mode": "REL", "bytes": 2, "cycles": 2, "unofficial": false, "branch_cycles": 2, "page_cycles": 1, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "71": {"mnemonic": "ADC", "mode": "IND_Y", "bytes": 2, "cycles": 5, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "72": {"mnemonic": "JAM", "mode": "IMP", "bytes": 1, "cycles": 0, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "73": {"mnemonic": "RRA", "mode": "IND_Y", "bytes": 2, "cycles": 8, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "74": {"mnemonic": "NOP", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "75": {"mnemonic": "ADC", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "76": {"mnemonic": "ROR", "mode": "ZP_X", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "77": {"mnemonic": "RRA", "mode": "ZP_X", "bytes": 2, "cycles": 6, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "78": {"mnemonic": "SEI", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "1", "D": "-"}},
  "79": {"mnemonic": "ADC", "mode": "ABS_Y", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "7A": {"mnemonic": "NOP", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "7B": {"mnemonic": "RRA", "mode": "ABS_Y", "bytes": 3, "cycles": 7, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "7C": {"mnemonic": "NOP", "mode": "ABS_X", "bytes": 3, "cycles": 4, "unofficial": true, "page_cycles": 1, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "7D": {"mnemonic": "ADC", "mode": "ABS_X", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "7E": {"mnemonic": "ROR", "mode": "ABS_X", "bytes": 3, "cycles": 7, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "7F": {"mnemonic": "RRA", "mode": "ABS_X", "bytes": 3, "cycles": 7, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "80": {"mnemonic": "NOP", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "81": {"mnemonic": "STA", "mode": "IND_X", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "82": {"mnemonic": "NOP", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "83": {"mnemonic": "SAX", "mode": "IND_X", "bytes": 2, "cycles": 6, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "84": {"mnemonic": "STY", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "85": {"mnemonic": "STA", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "86": {"mnemonic": "STX", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "87": {"mnemonic": "SAX", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "88": {"mnemonic": "DEY", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "89": {"mnemonic": "NOP", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "8A": {"mnemonic": "TXA", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "8B": {"mnemonic": "XAA", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "8C": {"mnemonic": "STY", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "8D": {"mnemonic": "STA", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "8E": {"mnemonic": "STX", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "8F": {"mnemonic": "SAX", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "90": {"mnemonic": "BCC", "mode": "REL", "bytes": 2, "cycles": 2, "unofficial": false, "branch_cycles": 2, "page_cycles": 1, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "91": {"mnemonic": "STA", "mode": "IND_Y", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "92": {"mnemonic": "JAM", "mode": "IMP", "bytes": 1, "cycles": 0, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "93": {"mnemonic": "AHX", "mode": "IND_Y", "bytes": 2, "cycles": 6, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "94": {"mnemonic": "STY", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "95": {"mnemonic": "STA", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "96": {"mnemonic": "STX", "mode": "ZP_Y", "bytes": 2, "cycles": 4, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "97": {"mnemonic": "SAX", "mode": "ZP_Y", "bytes": 2, "cycles": 4, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "98": {"mnemonic": "TYA", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "99": {"mnemonic": "STA", "mode": "ABS_Y", "bytes": 3, "cycles": 5, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "9A": {"mnemonic": "TXS", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "9B": {"mnemonic": "TAS", "mode": "ABS_Y", "bytes": 3, "cycles": 5, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "9C": {"mnemonic": "SHY", "mode": "ABS_X", "bytes": 3, "cycles": 5, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "9D": {"mnemonic": "STA", "mode": "ABS_X", "bytes": 3, "cycles": 5, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "9E": {"mnemonic": "SHX", "mode": "ABS_Y", "bytes": 3, "cycles": 5, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "9F": {"mnemonic": "AHX", "mode": "ABS_Y", "bytes": 3, "cycles": 5, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "A0": {"mnemonic": "LDY", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "A1": {"mnemonic": "LDA", "mode": "IND_X", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "A2": {"mnemonic": "LDX", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "A3": {"mnemonic": "LAX", "mode": "IND_X", "bytes": 2, "cycles": 6, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "A4": {"mnemonic": "LDY", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "A5": {"mnemonic": "LDA", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "A6": {"mnemonic": "LDX", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "A7": {"mnemonic": "LAX", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "A8": {"mnemonic": "TAY", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "A9": {"mnemonic": "LDA", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "AA": {"mnemonic": "TAX", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "AB": {"mnemonic": "LAX", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "AC": {"mnemonic": "LDY", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "AD": {"mnemonic": "LDA", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "AE": {"mnemonic": "LDX", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "AF": {"mnemonic": "LAX", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "B0": {"mnemonic": "BCS", "mode": "REL", "bytes": 2, "cycles": 2, "unofficial": false, "branch_cycles": 2, "page_cycles": 1, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "B1": {"mnemonic": "LDA", "mode": "IND_Y", "bytes": 2, "cycles": 5, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "B2": {"mnemonic": "JAM", "mode": "IMP", "bytes": 1, "cycles": 0, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "B3": {"mnemonic": "LAX", "mode": "IND_Y", "bytes": 2, "cycles": 5, "unofficial": true, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "B4": {"mnemonic": "LDY", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "B5": {"mnemonic": "LDA", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "B6": {"mnemonic": "LDX", "mode": "ZP_Y", "bytes": 2, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "B7": {"mnemonic": "LAX", "mode": "ZP_Y", "bytes": 2, "cycles": 4, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "B8": {"mnemonic": "CLV", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "0", "I": "-", "D": "-"}},
  "B9": {"mnemonic": "LDA", "mode": "ABS_Y", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "BA": {"mnemonic": "TSX", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "BB": {"mnemonic": "LAS", "mode": "ABS_Y", "bytes": 3, "cycles": 4, "unofficial": true, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "BC": {"mnemonic": "LDY", "mode": "ABS_X", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "BD": {"mnemonic": "LDA", "mode": "ABS_X", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "BE": {"mnemonic": "LDX", "mode": "ABS_Y", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "BF": {"mnemonic": "LAX", "mode": "ABS_Y", "bytes": 3, "cycles": 4, "unofficial": true, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "C0": {"mnemonic": "CPY", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "C1": {"mnemonic": "CMP", "mode": "IND_X", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "C2": {"mnemonic": "NOP", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "C3": {"mnemonic": "DCP", "mode": "IND_X", "bytes": 2, "cycles": 8, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "C4": {"mnemonic": "CPY", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "C5": {"mnemonic": "CMP", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "C6": {"mnemonic": "DEC", "mode": "ZP", "bytes": 2, "cycles": 5, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "C7": {"mnemonic": "DCP", "mode": "ZP", "bytes": 2, "cycles": 5, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "C8": {"mnemonic": "INY", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "C9": {"mnemonic": "CMP", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "CA": {"mnemonic": "DEX", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "CB": {"mnemonic": "AXS", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "CC": {"mnemonic": "CPY", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "CD": {"mnemonic": "CMP", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "CE": {"mnemonic": "DEC", "mode": "ABS", "bytes": 3, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "CF": {"mnemonic": "DCP", "mode": "ABS", "bytes": 3, "cycles": 6, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "D0": {"mnemonic": "BNE", "mode": "REL", "bytes": 2, "cycles": 2, "unofficial": false, "branch_cycles": 2, "page_cycles": 1, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "D1": {"mnemonic": "CMP", "mode": "IND_Y", "bytes": 2, "cycles": 5, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "D2": {"mnemonic": "JAM", "mode": "IMP", "bytes": 1, "cycles": 0, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "D3": {"mnemonic": "DCP", "mode": "IND_Y", "bytes": 2, "cycles": 8, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "D4": {"mnemonic": "NOP", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "D5": {"mnemonic": "CMP", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "D6": {"mnemonic": "DEC", "mode": "ZP_X", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "D7": {"mnemonic": "DCP", "mode": "ZP_X", "bytes": 2, "cycles": 6, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "D8": {"mnemonic": "CLD", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "0"}},
  "D9": {"mnemonic": "CMP", "mode": "ABS_Y", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "DA": {"mnemonic": "NOP", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "DB": {"mnemonic": "DCP", "mode": "ABS_Y", "bytes": 3, "cycles": 7, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "DC": {"mnemonic": "NOP", "mode": "ABS_X", "bytes": 3, "cycles": 4, "unofficial": true, "page_cycles": 1, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "DD": {"mnemonic": "CMP", "mode": "ABS_X", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "DE": {"mnemonic": "DEC", "mode": "ABS_X", "bytes": 3, "cycles": 7, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "DF": {"mnemonic": "DCP", "mode": "ABS_X", "bytes": 3, "cycles": 7, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "E0": {"mnemonic": "CPX", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "E1": {"mnemonic": "SBC", "mode": "IND_X", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "E2": {"mnemonic": "NOP", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "E3": {"mnemonic": "ISC", "mode": "IND_X", "bytes": 2, "cycles": 8, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "E4": {"mnemonic": "CPX", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "E5": {"mnemonic": "SBC", "mode": "ZP", "bytes": 2, "cycles": 3, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "E6": {"mnemonic": "INC", "mode": "ZP", "bytes": 2, "cycles": 5, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "E7": {"mnemonic": "ISC", "mode": "ZP", "bytes": 2, "cycles": 5, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "E8": {"mnemonic": "INX", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "E9": {"mnemonic": "SBC", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "EA": {"mnemonic": "NOP", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "EB": {"mnemonic": "SBC", "mode": "IMM", "bytes": 2, "cycles": 2, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "EC": {"mnemonic": "CPX", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "-", "I": "-", "D": "-"}},
  "ED": {"mnemonic": "SBC", "mode": "ABS", "bytes": 3, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "EE": {"mnemonic": "INC", "mode": "ABS", "bytes": 3, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "EF": {"mnemonic": "ISC", "mode": "ABS", "bytes": 3, "cycles": 6, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "F0": {"mnemonic": "BEQ", "mode": "REL", "bytes": 2, "cycles": 2, "unofficial": false, "branch_cycles": 2, "page_cycles": 1, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "F1": {"mnemonic": "SBC", "mode": "IND_Y", "bytes": 2, "cycles": 5, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "F2": {"mnemonic": "JAM", "mode": "IMP", "bytes": 1, "cycles": 0, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "F3": {"mnemonic": "ISC", "mode": "IND_Y", "bytes": 2, "cycles": 8, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "F4": {"mnemonic": "NOP", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "F5": {"mnemonic": "SBC", "mode": "ZP_X", "bytes": 2, "cycles": 4, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "F6": {"mnemonic": "INC", "mode": "ZP_X", "bytes": 2, "cycles": 6, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "F7": {"mnemonic": "ISC", "mode": "ZP_X", "bytes": 2, "cycles": 6, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "F8": {"mnemonic": "SED", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": false, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "1"}},
  "F9": {"mnemonic": "SBC", "mode": "ABS_Y", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "FA": {"mnemonic": "NOP", "mode": "IMP", "bytes": 1, "cycles": 2, "unofficial": true, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "FB": {"mnemonic": "ISC", "mode": "ABS_Y", "bytes": 3, "cycles": 7, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "FC": {"mnemonic": "NOP", "mode": "ABS_X", "bytes": 3, "cycles": 4, "unofficial": true, "page_cycles": 1, "flags_mod": {"N": "-", "Z": "-", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "FD": {"mnemonic": "SBC", "mode": "ABS_X", "bytes": 3, "cycles": 4, "unofficial": false, "page_cycles": 1, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}},
  "FE": {"mnemonic": "INC", "mode": "ABS_X", "bytes": 3, "cycles": 7, "unofficial": false, "flags_mod": {"N": "*", "Z": "*", "C": "-", "V": "-", "I": "-", "D": "-"}},
  "FF": {"mnemonic": "ISC", "mode": "ABS_X", "bytes": 3, "cycles": 7, "unofficial": true, "flags_mod": {"N": "*", "Z": "*", "C": "*", "V": "*", "I": "-", "D": "-"}}
};